# Generated by Django 3.2.4 on 2021-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
