# Generated by Django 3.2.4 on 2021-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_student_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
