# Generated by Django 3.2.4 on 2021-06-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_user_is_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
