# Generated by Django 3.2.4 on 2021-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_student_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='english',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hindi',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sub1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sub2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sub3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
