# Generated by Django 3.2.4 on 2021-06-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_student_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='has_password_changed',
        ),
    ]
