# Generated by Django 3.2.4 on 2021-06-11 10:50

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_schoolprofile_has_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='english',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[data.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='hindi',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[data.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[data.validators.validate_marks]),
        ),
    ]
