# Generated by Django 3.2.4 on 2021-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20210611_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sub3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
