# Generated by Django 3.2.4 on 2021-06-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_student_sub3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_update', 'Can update the data of students'), ('can_change_password', 'Can change the password of school user')]},
        ),
    ]
